import Footer from "@/components/footer/Footer";
import SNavbar from "@/components/navbar/SNavbar";
import { Inter } from "next/font/google";
import { cookies } from "next/headers";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Saidur Consulting",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    const access = cookies().get("prospect");
    console.log(access);
    return (
        <html lang="en">
            <body className={`${inter.className}`}>
                <SNavbar />
                {children}

                <Footer />
            </body>
        </html>
    );
}
